[project]
name = "embed-binary-tools"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.5,<3.13"
pip = ">=24.2,<25"
build = ">=0.7.0,<0.8"
