[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hello"
authors = [
    {name = "Sébastien Boisgérault", email = "Sebastien.Boisgerault@gmail.com"},
]
version = "0.0.1"

[project.scripts]
hello-world = "hello:main"